-- =========================================================================
-- SE2026 Portal — Iterasi 23: Data tagging & audit geospasial
-- Snapshot baru diproses di staging dan baru aktif setelah finalisasi sukses.
-- =========================================================================

CREATE TABLE IF NOT EXISTS tagging_import_batch (
  id                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  filename               VARCHAR(255) NOT NULL,
  file_sha256            CHAR(64) NOT NULL,
  file_size              BIGINT UNSIGNED NOT NULL DEFAULT 0,
  status                 ENUM('uploading','processing','completed','failed','revoked') NOT NULL DEFAULT 'uploading',
  is_active              TINYINT(1) NOT NULL DEFAULT 0,
  raw_rows               INT UNSIGNED NOT NULL DEFAULT 0,
  uploaded_rows          INT UNSIGNED NOT NULL DEFAULT 0,
  unique_assignments     INT UNSIGNED NOT NULL DEFAULT 0,
  duplicate_rows         INT UNSIGNED NOT NULL DEFAULT 0,
  status_conflicts       INT UNSIGNED NOT NULL DEFAULT 0,
  exact_point_groups     INT UNSIGNED NOT NULL DEFAULT 0,
  near_point_groups      INT UNSIGNED NOT NULL DEFAULT 0,
  missing_coordinates    INT UNSIGNED NOT NULL DEFAULT 0,
  low_accuracy           INT UNSIGNED NOT NULL DEFAULT 0,
  unmapped_codes         INT UNSIGNED NOT NULL DEFAULT 0,
  outside_subsls         INT UNSIGNED NOT NULL DEFAULT 0,
  imported_by            INT NULL,
  error_summary          TEXT NULL,
  created_at             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  completed_at           TIMESTAMP(3) NULL,
  INDEX idx_tag_batch_status (status, created_at),
  INDEX idx_tag_batch_active (is_active),
  INDEX idx_tag_batch_hash (file_sha256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tagging_import_stage (
  batch_id                  BIGINT UNSIGNED NOT NULL,
  source_row                INT UNSIGNED NOT NULL,
  assignment_id             VARCHAR(64) NOT NULL,
  assignment_status_alias   VARCHAR(100) NOT NULL,
  level_6_full_code         VARCHAR(32) NOT NULL,
  nama_usaha_bang           VARCHAR(255) NULL,
  nama_kk                   VARCHAR(255) NULL,
  ada_keluarga_label        VARCHAR(80) NULL,
  ada_bang_usaha_label      VARCHAR(80) NULL,
  geotag_accuracy           DECIMAL(12,3) NULL,
  geotag_latitude           DECIMAL(11,8) NULL,
  geotag_longitude          DECIMAL(11,8) NULL,
  row_hash                  CHAR(64) NOT NULL,
  PRIMARY KEY (batch_id, source_row),
  INDEX idx_tag_stage_assignment (batch_id, assignment_id),
  INDEX idx_tag_stage_coordinate (batch_id, geotag_latitude, geotag_longitude),
  INDEX idx_tag_stage_hash (batch_id, row_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tagging_assignment (
  batch_id                 BIGINT UNSIGNED NOT NULL,
  assignment_id            VARCHAR(64) NOT NULL,
  status_alias             VARCHAR(100) NOT NULL,
  status_conflict          TINYINT(1) NOT NULL DEFAULT 0,
  status_variants_json     JSON NOT NULL,
  source_rows_json         JSON NOT NULL,
  duplicate_occurrences    INT UNSIGNED NOT NULL DEFAULT 0,
  level_6_full_code        VARCHAR(32) NOT NULL,
  kdprov                   VARCHAR(2) NULL,
  kdkab                    VARCHAR(4) NULL,
  kdkec                    VARCHAR(7) NULL,
  kddesa                   VARCHAR(10) NULL,
  idsls                    VARCHAR(14) NULL,
  idsubsls                 VARCHAR(16) NULL,
  nmkec                    VARCHAR(150) NULL,
  nmdesa                   VARCHAR(150) NULL,
  nmsls                    VARCHAR(150) NULL,
  nama_usaha_bang          VARCHAR(255) NULL,
  nama_kk                  VARCHAR(255) NULL,
  ada_keluarga_label       VARCHAR(80) NULL,
  ada_bang_usaha_label     VARCHAR(80) NULL,
  geotag_accuracy          DECIMAL(12,3) NULL,
  geotag_latitude          DECIMAL(11,8) NULL,
  geotag_longitude         DECIMAL(11,8) NULL,
  has_coordinate           TINYINT(1) NOT NULL DEFAULT 0,
  mapped_code              TINYINT(1) NOT NULL DEFAULT 0,
  inside_subsls            TINYINT(1) NULL,
  exact_cluster_key        CHAR(32) NULL,
  exact_cluster_size       INT UNSIGNED NOT NULL DEFAULT 0,
  near_cluster_key         CHAR(32) NULL,
  near_cluster_size        INT UNSIGNED NOT NULL DEFAULT 0,
  warning_count            INT UNSIGNED NOT NULL DEFAULT 0,
  created_at               TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (batch_id, assignment_id),
  INDEX idx_tag_assignment_filter (batch_id, kdkec, kddesa, idsls, idsubsls),
  INDEX idx_tag_assignment_status (batch_id, status_alias),
  INDEX idx_tag_assignment_warning (batch_id, warning_count),
  INDEX idx_tag_assignment_coordinate (batch_id, geotag_latitude, geotag_longitude),
  INDEX idx_tag_assignment_exact (batch_id, exact_cluster_key),
  INDEX idx_tag_assignment_near (batch_id, near_cluster_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tagging_warning (
  id                BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  batch_id          BIGINT UNSIGNED NOT NULL,
  warning_type      VARCHAR(40) NOT NULL,
  severity          ENUM('info','warning','critical') NOT NULL DEFAULT 'warning',
  assignment_id     VARCHAR(64) NULL,
  cluster_key       CHAR(32) NULL,
  related_count     INT UNSIGNED NOT NULL DEFAULT 1,
  distance_m        DECIMAL(8,2) NULL,
  details_json      JSON NULL,
  created_at        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_tag_warning_batch_type (batch_id, warning_type),
  INDEX idx_tag_warning_assignment (batch_id, assignment_id),
  INDEX idx_tag_warning_cluster (batch_id, cluster_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
