export const mockStats = {
  total_target: 9960,
  total_realisasi: 2240,
  persentase: 22.5,
  kecamatan_count: 4,
  petugas_aktif: 12,
  hari_tersisa: 121,
}

export const mockProgress = [
  { id: 1,  kecamatan: 'Muara Beliti',              target_usaha: 1240, realisasi: 620, petugas_count: 4, status: 'berlangsung' },
  { id: 2,  kecamatan: 'Tugumulyo',                 target_usaha: 1180, realisasi: 480, petugas_count: 4, status: 'berlangsung' },
  { id: 3,  kecamatan: 'BTS Ulu',                   target_usaha: 980,  realisasi: 310, petugas_count: 3, status: 'berlangsung' },
  { id: 4,  kecamatan: 'Muara Lakitan',             target_usaha: 920,  realisasi: 260, petugas_count: 3, status: 'berlangsung' },
  { id: 5,  kecamatan: 'Megang Sakti',              target_usaha: 890,  realisasi: 0,   petugas_count: 3, status: 'belum' },
  { id: 6,  kecamatan: 'Rawas Ulu',                 target_usaha: 870,  realisasi: 0,   petugas_count: 3, status: 'belum' },
  { id: 7,  kecamatan: 'Karang Jaya',               target_usaha: 760,  realisasi: 0,   petugas_count: 3, status: 'belum' },
  { id: 8,  kecamatan: 'Rawas Ilir',                target_usaha: 620,  realisasi: 0,   petugas_count: 2, status: 'belum' },
  { id: 9,  kecamatan: 'Jayaloka',                  target_usaha: 540,  realisasi: 0,   petugas_count: 2, status: 'belum' },
  { id: 10, kecamatan: 'Sukakarya',                 target_usaha: 480,  realisasi: 0,   petugas_count: 2, status: 'belum' },
  { id: 11, kecamatan: 'Bulang Tengah Suku Ulu',    target_usaha: 410,  realisasi: 0,   petugas_count: 2, status: 'belum' },
  { id: 12, kecamatan: 'STL Ulu Terawas',           target_usaha: 380,  realisasi: 0,   petugas_count: 2, status: 'belum' },
  { id: 13, kecamatan: 'Selangit',                  target_usaha: 350,  realisasi: 0,   petugas_count: 1, status: 'belum' },
  { id: 14, kecamatan: 'Tiang Pumpung Kepungut',    target_usaha: 340,  realisasi: 0,   petugas_count: 1, status: 'belum' },
].map(k => ({ ...k, persentase: k.target_usaha > 0 ? Math.round((k.realisasi / k.target_usaha) * 100) : 0 }))

export const mockPosts = [
  {
    id: 1,
    judul: 'Kick-off Pencacahan SE2026 di Kecamatan Muara Beliti',
    slug: 'kickoff-pencacahan-muara-beliti',
    kategori: 'berita',
    excerpt: 'BPS Kabupaten Musi Rawas secara resmi memulai pencacahan SE2026 di Kecamatan Muara Beliti dengan melibatkan 4 petugas lapangan terlatih.',
    thumbnail: null,
    author: 'BPS Kab. Musi Rawas',
    published: true,
    created_at: '2026-05-01T09:00:00Z',
  },
  {
    id: 2,
    judul: 'Pelatihan Petugas SE2026 Gelombang II Selesai Dilaksanakan',
    slug: 'pelatihan-petugas-gelombang-2',
    kategori: 'sosialisasi',
    excerpt: 'Sebanyak 28 petugas lapangan dan 6 koordinator kecamatan telah menyelesaikan pelatihan teknis pencacahan SE2026 selama 3 hari.',
    thumbnail: null,
    author: 'BPS Kab. Musi Rawas',
    published: true,
    created_at: '2026-04-28T10:00:00Z',
  },
  {
    id: 3,
    judul: 'Infografis: 18 Kategori Usaha yang Dicacah dalam SE2026',
    slug: 'infografis-18-kategori-usaha',
    kategori: 'infografis',
    excerpt: 'Sensus Ekonomi 2026 mencakup 18 kategori lapangan usaha non-pertanian, dari perdagangan hingga jasa keuangan.',
    thumbnail: null,
    author: 'BPS Kab. Musi Rawas',
    published: true,
    created_at: '2026-04-20T08:00:00Z',
  },
  {
    id: 4,
    judul: 'Pengumuman: Jadwal Sosialisasi SE2026 Tingkat Desa',
    slug: 'jadwal-sosialisasi-tingkat-desa',
    kategori: 'pengumuman',
    excerpt: 'BPS Kab. Musi Rawas akan menyelenggarakan sosialisasi SE2026 di seluruh desa/kelurahan pada bulan Mei 2026.',
    thumbnail: null,
    author: 'BPS Kab. Musi Rawas',
    published: true,
    created_at: '2026-04-15T07:00:00Z',
  },
  {
    id: 5,
    judul: 'Video: Cara Mengisi Kuesioner SE2026 Online',
    slug: 'video-cara-isi-kuesioner-online',
    kategori: 'video',
    excerpt: 'Panduan lengkap pengisian kuesioner SE2026 secara online melalui portal sensus.bps.go.id/se2026.',
    thumbnail: null,
    author: 'BPS Kab. Musi Rawas',
    published: true,
    created_at: '2026-04-10T11:00:00Z',
  },
  {
    id: 6,
    judul: 'Persiapan SE2026: BPS Musi Rawas Lakukan Pemetaan Blok Sensus',
    slug: 'persiapan-pemetaan-blok-sensus',
    kategori: 'berita',
    excerpt: 'Tim BPS Kabupaten Musi Rawas telah menyelesaikan pemutakhiran peta blok sensus untuk keperluan pendataan SE2026.',
    thumbnail: null,
    author: 'BPS Kab. Musi Rawas',
    published: true,
    created_at: '2026-03-25T09:00:00Z',
  },
]

export const kategoriUsaha = [
  { icon: '🏪', nama: 'Perdagangan Besar & Eceran', color: '#E8751A' },
  { icon: '🍽️', nama: 'Penyediaan Akomodasi & Makan Minum', color: '#F5A623' },
  { icon: '🏭', nama: 'Industri Pengolahan', color: '#C85E0A' },
  { icon: '🏗️', nama: 'Konstruksi', color: '#00A651' },
  { icon: '🚗', nama: 'Transportasi & Pergudangan', color: '#3D3D3D' },
  { icon: '💻', nama: 'Informasi & Komunikasi', color: '#1877F2' },
  { icon: '🏦', nama: 'Jasa Keuangan & Asuransi', color: '#6B21A8' },
  { icon: '🏠', nama: 'Real Estate', color: '#0F766E' },
  { icon: '⚡', nama: 'Pengadaan Listrik & Gas', color: '#D97706' },
  { icon: '💧', nama: 'Pengadaan Air & Pengelolaan Sampah', color: '#0284C7' },
  { icon: '🔧', nama: 'Jasa Profesional & Teknik', color: '#7C3AED' },
  { icon: '🏥', nama: 'Kesehatan & Kegiatan Sosial', color: '#DC2626' },
  { icon: '🎓', nama: 'Pendidikan', color: '#059669' },
  { icon: '🎭', nama: 'Kesenian & Hiburan', color: '#DB2777' },
  { icon: '🔧', nama: 'Reparasi & Perawatan', color: '#92400E' },
  { icon: '📦', nama: 'Jasa Lainnya', color: '#6B6B6B' },
  { icon: '🌊', nama: 'Perikanan', color: '#0369A1' },
  { icon: '⚒️', nama: 'Pertambangan & Penggalian', color: '#78350F' },
]

export const jadwalTimeline = [
  {
    id: 1,
    judul: 'Sosialisasi & Persiapan',
    periode: 'Jan – Apr 2026',
    status: 'selesai',
    deskripsi: 'Sosialisasi kepada pelaku usaha, pelatihan petugas, dan persiapan peta blok sensus.',
    icon: '📢',
  },
  {
    id: 2,
    judul: 'Pelatihan Petugas',
    periode: 'Apr – Mei 2026',
    status: 'selesai',
    deskripsi: 'Pelatihan teknis pencacahan bagi 34 petugas lapangan dan 6 koordinator kecamatan.',
    icon: '🎓',
  },
  {
    id: 3,
    judul: 'Pencacahan Online',
    periode: 'Mei – Agt 2026',
    status: 'aktif',
    deskripsi: 'Pengisian kuesioner SE2026 secara mandiri oleh pelaku usaha melalui portal online.',
    icon: '💻',
  },
  {
    id: 4,
    judul: 'Pendataan Door to Door',
    periode: '15 Jun – 31 Agt 2026',
    status: 'aktif',
    deskripsi: 'Kunjungan langsung petugas ke lokasi usaha untuk pendataan menyeluruh.',
    icon: '📍',
  },
  {
    id: 5,
    judul: 'Pengolahan & Validasi',
    periode: 'Sep – Nov 2026',
    status: 'akan-datang',
    deskripsi: 'Pengolahan data hasil pencacahan, validasi, dan koreksi data oleh tim BPS.',
    icon: '🗄️',
  },
  {
    id: 6,
    judul: 'Publikasi Hasil',
    periode: 'Des 2026',
    status: 'akan-datang',
    deskripsi: 'Rilis publikasi resmi hasil Sensus Ekonomi 2026 Kabupaten Musi Rawas.',
    icon: '📊',
  },
]
